<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Tests.fs" />
    <Compile Include="IntegrationTests.fs" />
    <Compile Include="ConnectionTests.fs" />
    <Compile Include="ViewBindingTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Vigila.Application/Vigila.Application.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>